### Feature Inventory — UPDATE (PUT) / UPDATE (PATCH)
### Leyenda: SIN AUTH (sin middleware JWT / sin autenticación)

@baseUrl = http://localhost:3000
@id = 1

# @name updateInventoryPut
PUT {{baseUrl}}/api/inventarios/{{id}}
Content-Type: application/json

{
  "quantity": 30,
  "minStock": 8
}

###

# @name updateInventoryPatch
PATCH {{baseUrl}}/api/inventarios/{{id}}
Content-Type: application/json

{
  "quantity": 25
}
