### Feature Purchase — GET ALL / GET ONE
### Leyenda: SIN AUTH (sin middleware JWT / sin autenticación)

@baseUrl = http://localhost:3000
@id = 1

# @name getAllPurchases
GET {{baseUrl}}/api/compras

###

# @name getOnePurchase
GET {{baseUrl}}/api/compras/{{id}}
